### PR TITLE
Fix get migrated timestamp

### LINKED ISSUE #31: Show versions fails due to a 'A non well formed numeric value encountered'
Error (edited to remove our specific app file paths etc):
```
/usr/bin/php app/console mongodb:migrations:status -v --env=it --dm=domain_document_manager --show-versions

 == Configuration

    >> Name:                                MongoDB Migrations
    >> Database Driver:                     MongoDB
    >> Database Name:                       domain
    >> Configuration Source:                manually configured
    >> Version Collection Name:             migration_versions
    >> Migrations Namespace:                App\Infrastructure\InfrastructureBundle\Migrations\MongoDB
    >> Migrations Directory:                <PATH>Migrations/MongoDB
    >> Current Version:                     2018-04-11 00:20:11 (20180411002011)
    >> Latest Version:                      2018-04-11 00:20:11 (20180411002011)
    >> Executed Migrations:                 12
    >> Executed Unavailable Migrations:     4
    >> Available Migrations:                12
    >> New Migrations:                      0

 == Available Migration Versions


In StatusCommand.php line 129:
                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: A non well formed numeric value encountered        
                                                             

Exception trace:
 AntiMattr\MongoDB\Migrations\Tools\Console\Command\StatusCommand->execute() at PATH/vendor/doesntmattr/mongodb-migrations-bundle/Command/MigrationsStatusCommand.php:41
 AntiMattr\Bundle\MongoDBMigrationsBundle\Command\MigrationsStatusCommand->execute() at PATH/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at PATH/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at PATH/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at PATH/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
 Symfony\Component\Console\Application->doRun() at PATH/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at PATH/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at PATH/app/console:27

mongodb:migrations:status [--show-versions] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--dm [DM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

This was produced from `master`. This is probably due to the change introduced in #30 as we've changed it from `\MongoTimestamp` to `MongoDB\BSON\UTCDateTime`. Just needs something to normalise the date as the db may have a mix of these two types.

Alternatively we should ship something to migrate all the dates?

Hopefully `\MongoTimestamp` is actually `MongoDB\BSON\Timestamp`. Probably should check that otherwise we will need a migration to ensure no one using `v2.0` is still requiring the `mongodb-php-adapter`.

### PR DESCRIPTION
**Pull request by redthor**
Resolves #31

### CODE REVIEW

File: src/AntiMattr/MongoDB/Migrations/Configuration/Timestamp.php [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+    }
+
+    /**
+     * __invoke.
+     *
+     * @param mixed $t
+     *
+     * @return int
+     */
+    public function __invoke($t): int
```
Comment (caciobanu) [inline src/AntiMattr/MongoDB/Migrations/Configuration/Timestamp.php]: I ca't find any usage of this method. Can we just drop it ?

File: src/AntiMattr/MongoDB/Migrations/Configuration/Timestamp.php [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+ * attribute.
+ *
+ * @author Douglas Reith <douglas@reith.com.au>
+ */
+class Timestamp
+{
+    private $t;
+
+    /**
+     * __construct.
```
Comment (caciobanu) [inline src/AntiMattr/MongoDB/Migrations/Configuration/Timestamp.php]: We should drop methods name from comments.

**Comment by redthor** [comment]
great feedback @caciobanu - thank you
